# Q-Learning with FrozenLake 4x4

![alt text](http://simoninithomas.com/drlc/Qlearning/frozenlake4x4.png)



In [1]:
import numpy as np
import gym
import random
import time

## Step 1: Create the environment 



In [2]:
env = gym.make("FrozenLake-v1", render_mode='human')

c:\Users\Amin\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
c:\Users\Amin\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\wrappers\step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


## Step 2: Create the Q-table and initialize it 


In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n
print("Action Size: " , action_size, "(0: LEFT - 1: DOWN - 2: RIGHT - 3: UP)","\nState Size: ", state_size)

Action Size:  4 (0: LEFT - 1: DOWN - 2: RIGHT - 3: UP) 
State Size:  16


In [4]:
# Create our Q table with state_size rows and action_size columns (
qtable = np.zeros((state_size, action_size))
print("Each row is State & Each column is Action\n------------------\n", qtable)

Each row is State & Each column is Action
------------------
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Step 3: Create the hyperparameters 


In [5]:
total_episodes = 20000       # Total episodes
learning_rate = 0.7          # Learning rate
max_steps = 99               # Max steps per episode
gamma = 0.95                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005            # Exponential decay rate for exploration prob

## Step 4: The Q-learning algorithm 
  ![alt text](http://simoninithomas.com/drlc/Qlearning//qtable_algo.png)


In [12]:
# 1. List of rewards
rewards = []

# 2. Until learning is stopped
Start = time.time()
for episode in range(100):
    print(f"\n---------- Episode: {episode} ----------\n")
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        print(f"Step: {step}")
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
            #print(exp_exp_tradeoff, "action", action)

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
            #print("action random", action)
            
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True and reward == 1: 
            print("WIN")
            break
        if done == True: 
            print("Dead")
            break
         
    # Reduce epsilon (because we need less and less exploration) # https://towardsdatascience.com/learning-rate-schedules-and-adaptive-learning-rate-methods-for-deep-learning-2c8f433990d1
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) # https://machinelearningmastery.com/using-learning-rate-schedules-deep-learning-models-python-keras/ 
    rewards.append(total_rewards)
    
End = time.time()
Time = End - Start
print ("Score over time: ",  sum(rewards)/total_episodes)
print('Execution time: {:.3f}'.format(Time), 'seconds')
float_formatter = "{:.9f}".format # https://stackoverflow.com/questions/21008858/formatting-floats-in-a-numpy-array
np.set_printoptions(formatter={'float_kind': float_formatter})
print("\n------------------------------------------\n")
print(qtable)


---------- Episode: 0 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7
Step: 8
Step: 9
Step: 10
Step: 11
Step: 12
Step: 13
Step: 14
Step: 15
Step: 16
Step: 17
Step: 18
Step: 19

---------- Episode: 1 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7
Step: 8
Step: 9
Step: 10
Step: 11
Step: 12
Step: 13
Step: 14
Step: 15
Dead

---------- Episode: 2 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Dead

---------- Episode: 3 ----------

Step: 0
Step: 1
Step: 2
Dead

---------- Episode: 4 ----------

Step: 0
Step: 1
Step: 2
Dead

---------- Episode: 5 ----------

Step: 0
Step: 1
Step: 2
Dead

---------- Episode: 6 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Dead

---------- Episode: 7 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7
Step: 8
Dead

---------- Episode: 8 ----------

Step: 0
Step: 1
Step: 2
Step: 3
Step: 4
Step: 5
Step: 6
Step: 7
Dead

---------- Episode: 9 ----------

Step: 0
Step: 1
St

## Step 5: Use our Q-table to play FrozenLake ! 


In [14]:
env.reset()
max_steps = 99
n = 100
win = 0
loss = 0
for episode in range(n):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE: ", episode)

    for step in range(max_steps):
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if new_state == 15:
                win += 1
                print(">> We reached our Goal")
            else:
                loss += 1
                print(">> We fell into a hole")
            
            # We print the number of step it took.
            print("Number of steps: ", step)
            
            break
        state = new_state
env.close()
print("****************************************************")
print(f"\nTotal Episode: {n}\nMax Step per Episode: {max_steps}\nWin: {win}\nLoss: {loss}")

****************************************************
EPISODE:  0
>> We fell into a hole
Number of steps:  23
****************************************************
EPISODE:  1
>> We fell into a hole
Number of steps:  17
****************************************************
EPISODE:  2
>> We fell into a hole
Number of steps:  33
****************************************************
EPISODE:  3
>> We fell into a hole
Number of steps:  9
****************************************************
EPISODE:  4
>> We fell into a hole
Number of steps:  18
****************************************************
EPISODE:  5
>> We reached our Goal
Number of steps:  8
****************************************************
EPISODE:  6
>> We fell into a hole
Number of steps:  9
****************************************************
EPISODE:  7
>> We reached our Goal
Number of steps:  16
****************************************************
EPISODE:  8
>> We fell into a hole
Number of steps:  11
**********************